name: gm_upper-build

on:
  push:
    paths:
      - ".github/workflows/gm_upper-build.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: pwd && ls -al
      - uses: actions/checkout@v4
      - run: pwd && ls -al
      - run: go version
      - uses: actions/setup-go@v5
        with:
          # go-version: '1.22'
          go-version-file: ./upper/go.mod
          cache-dependency-path: ./upper/go.sum
      - run: go mod download
        working-directory: upper
      - run: |
          ls
          go build
          ls
          go test
        working-directory: upper
        name: build and test

